### ISSUE TITLE
new command looks for config in wrong place

### ISSUE THREAD

**Issue by robcaw** [vivait/TenantBundle#15]
`app/config/config_tenant_vivait.yml"` instead of `app/config/tenants/tenant_vivait.yml"` causing ansible to fail when running tenant commands

**Comment by robcaw** [comment]
I think I've solved this in vivadesk and is probably a non-issue. Before , all of the tenants have been stored in the config/tenants directory, but it seems that's not the best place for them from the looks of the new `bin/tenant` command behaviour.

My AppKernel was previously: 

```php
public function registerContainerConfiguration(LoaderInterface $loader)
    {
        $tenant = $this->getTenantRegistry()->getCurrent();

        if ($tenant) {
            $loader->load(__DIR__ . '/config/config_prod.yml');
            $loader->load(__DIR__ . '/config/tenants/' . $this->getEnvironment() . '.yml');
        } else {
            $loader->load(__DIR__ . '/config/config_' . $this->getEnvironment() . '.yml');
        }
    }
```

But I've changed it to (what I think is) the default Symfony behaviour:

```php
    public function registerContainerConfiguration(LoaderInterface $loader)
    {
        $loader->load(__DIR__ . '/config/config_' . $this->getEnvironment() . '.yml');
    }
```

The difference in loading configs this way is that I have to manually load each tenant config for during deployment instead of just getting all of the tenants in config/tenant:

`update.yml`

```yaml
- hosts: production
  tasks:
    - name: symlink tenant configs
      file: state=link src={{symfony2_project_root}}/shared/app/config/config_tenant_{{ item }}.yml dest={{symfony2_release_destination}}/app/config/config_tenant_{{ item }}.yml force=yes
      with_items:
        - vivait
        - commsave
```

Perhaps there's a better way of loading these configs so the tenants don't need to be specified.
